INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1001, 'JJam', 'Get AWS Certified', CURRENT_DATE(), false);
INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1002, 'JJI', 'Learn DevOps', CURRENT_DATE(), false);
INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1003, 'JJam', 'Learn Full Stack Development', CURRENT_DATE(), false);
